### ISSUE TITLE
problem in getting final opx & opy for writeMicroseconds command 

### ISSUE THREAD

**Issue by anillspawar** [Cyrilanthony777/Obstacle_Avoidance_Multirotor#1]
e1=d1-setpoint;
e2=d2-setpoint;
op1=e1_Kp;
op2=e2_Kp;
opx=CH1-op1+op2;         // opx=ch1-(d1_Kp-setpoint_Kp)+(d2_Kp-setpoint_Kp) = ch1-(d1_Kp)+(d2_Kp)
opy=CH2-op3+op4;         //        

//Now opx become independent of setpoint, so whats the use of setpoint?? please explain..

**Comment by Cyrilanthony777** [comment]
Setpoint is the minimum distance between sensor and obstacle below which the Collision avoidance kicks in.  d1-setpoint will not go negative instead it will be at zero .
please refer to  https://en.wikipedia.org/wiki/Proportional_control
